### ISSUE TITLE
Compound graph parent and children of a given node

### ISSUE THREAD

**Issue by jlzavitz** [cpettitt/dagre-d3#142]
How can I get access to parent and child nodes in a compound graph? When I call graph.setParent I get the same error as [the comment in this issue](https://github.com/cpettitt/dagre-d3/issues/110#issuecomment-63330324)

If I remove edges to the nodes where I call setParent then the error disappears but the chart structure just turns into a cluster. And if I don't do the setParent, logging  graph._parent or graph._children return undefined mappings to all nodes, no matter how deep in the structure they are.

Just not sure how the structure can be so well defined visually but I cannot seem to call parent/children on the node ids, as defined in the prototype functions.

**Comment by jlzavitz** [comment]
I assume this is what the successors/predecessors functions are for

**Comment by junneyang** [comment]
@jlzavitz 
how to solve this problem, waiting for your help, thanks
