### ISSUE TITLE
Multiple edges between two nodes?

### ISSUE THREAD

**Issue by seandilda** [cpettitt/dagre-d3#149]
I'm trying to render a process flow, which for various reasons passes from node A to B twice, but with different values (which leads to different classes being applied, etc).   I did some debugging, and it looks like when I call setEdge the second time for the same set of nodes, the first entry gets overwritten.

Is there any way to get these two edges to show up at the same time?

**Comment by leishman** [comment]
@seandilda Did you have any luck with this? I am working on the same problem.

**Comment by seandilda** [comment]
I have not :(  From the behavior I'm seeing, it looks like an intentional 'feature' of graphlib, so I doubt it'll be easy to get the behavior we're looking for.

At this point I'm planning on finding another graphing library, but I haven't had time to pick one out yet.

**Comment by cpettitt** [comment]
A multi-graph allows multiple, distinct edges between the same two pair of nodes: https://github.com/cpettitt/graphlib/wiki/API-Reference#multigraphs

**Comment by seandilda** [comment]
@cpettitt, thanks for the link!  That solved my problem.

I'd tried multigraph before, but I didn't assign a name, so it didn't fix the problem.  I tried again, assigning a unique name to each edge (just an incrementing index) and now everything works great.
