### ISSUE TITLE
edge path not correct after rerender

### ISSUE THREAD

**Issue by basmeesters** [cpettitt/dagre-d3#153]
I just started using dagre and liking it very much thus far. At the moment I am creating a graph which has collapsible nodes. So far, so good, but when I expand a node and collapse it again it gives a weird edge display.

At first it just looks like this:
![image](https://cloud.githubusercontent.com/assets/7426223/7248995/70297bb4-e817-11e4-84f4-a0e1bf03ffb4.png)

after expanding like this:
![image](https://cloud.githubusercontent.com/assets/7426223/7249048/bdaecd30-e817-11e4-9bbc-62da56f6615e.png)

and after collapsing like this:
![image](https://cloud.githubusercontent.com/assets/7426223/7249060/d496f6f8-e817-11e4-8e1a-7c91dfa6feff.png)

so the adding and deleting of the nodes goes all well (also very nice transition function!) only after rerendering it goes wrong. I use my own function update which calls this line: renderer.run(g, svg);

where renderer is a DagreD3.Renderer(). I see a lot of examples using Dagre.render() but for some reason that doesn't seem to work with mine. Can somebody tell me what's wrong?

**Comment by basmeesters** [comment]
Sorry... it had nothing to do with dagre, but with my own stupid mistake -_-'

**Comment by huyngoo** [comment]
Hi, how did you get the weird fill within your edge to go away?
