### ISSUE TITLE
param difference setParent / setNode

### ISSUE THREAD

**Issue by wetgi** [cpettitt/dagre-d3#161]
g.setNode(number,{label:demo}); 
g.setParent(modul.id, number.toString());

In setParent I need to cast number.toString()

**Comment by courtneymiller2010** [comment]
Can you give a jsfiddle with this bug? I'm not seeing this behavior [here] (http://jsfiddle.net/courtney_miller_2010/r0bu97vo/1/).

**Comment by wetgi** [comment]
http://jsfiddle.net/hhxdo6no/
Line 60

**Comment by courtneymiller2010** [comment]
So I slimmed it down to a simpler [example] (http://jsfiddle.net/courtney_miller_2010/r0bu97vo/3/). Using setParent with numbers cause some weird layout problems. If I try to create an edge to a node inside the weird cluster (4), I get the error: "Not possible to find intersection inside of the rectangle". As soon as setParent is changed to use strings, it works fine.

In your example, if you use numbers in setParent and comment out the relationships, it renders. It must be something in the layout engine that is causing this. But I can't pinpoint what it is exactly. 

For now, you have a workaround it looks like.

**Comment by cpettitt** [comment]
@courtneymiller2010 thanks for the reduction.

I'm pretty sure this is symptomatic of a problem with how parents are handled in graphlib. I'll spend some time tonight to confirm. If that's the case a more general fix will be trivial.

**Comment by cpettitt** [comment]
Fixed in dagre-d3 v0.4.4
