### ISSUE TITLE
text wrapping: labelCols not working anymore, any alternative?

### ISSUE THREAD

**Issue by christianvoigt** [cpettitt/dagre-d3#162]
Hi, I need to wrap my node labels. It seems this has been the way to do it without using html labels: https://github.com/cpettitt/dagre-d3/issues/22

But this doesn't work anymore and I haven't found it in the source code. Is there any alternative way of achieving the same thing?

**Comment by courtneymiller2010** [comment]
Looks like you can do it with '\n' in your labels. 

The code can be found in [AddTextLabels.js] (https://github.com/cpettitt/dagre-d3/blob/master/lib/label/add-text-label.js)

Here's an [example] (http://jsfiddle.net/courtney_miller_2010/77njof88/1/). The 4th green node from the left, "example new line" is wrapped.

Hope that helps!

**Comment by christianvoigt** [comment]
thanks, that helped. To insert the linebreaks I simply used the wordwrap function from: https://gist.github.com/mmcgrath/8783910

Now I also would like to use a slightly larger line spacing (https://github.com/cpettitt/dagre-d3/issues/132), but that's a minor issue.
