### ISSUE TITLE
Bower can't find gulp-jshint

### ISSUE THREAD

**Issue by john-coffey** [cpettitt/dagre-d3#168]
When I ``rm -rf bower_components && bower cache clean`` then ``bower install``:

```
bower gulp-jshint#^1.10.0                  ENOTFOUND Package gulp-jshint not found
```

Looks like bower doesn't know about ``gulp-jshint`` -
```
✗ bower info gulp-jshint
bower                        ENOTFOUND Package gulp-jshint not found
```

**Comment by cpettitt** [comment]
Ahh, I broke the bower.json file. There should be no dependency on gulp-jshint. Will fix and re-release shortly.

**Comment by cpettitt** [comment]
Please try the latest release (0.4.7).

**Comment by john-coffey** [comment]
All fixed - thanks!
