### ISSUE TITLE
How to make my nodes on the same level?

### ISSUE THREAD

**Issue by xp0522** [cpettitt/dagre-d3#173]
Hi,

I have been trying to use dagre-d3 to draw some graphs but have some trouble making the nodes aligned on the same line. So in the below picture, I want all the "Phase" nodes on the same line and all the "Task" nodes on the line below. How can I do that? I am using setNode to generate the nodes for my graph. Please help.....
![image](https://cloud.githubusercontent.com/assets/12562775/7834222/05b64036-0465-11e5-8e7d-1d375c1fbe60.png)

Thanks!

**Comment by cpettitt** [comment]
Dagre does not give you enough control to get what you want currently. You can get close:

http://cpettitt.github.io/project/dagre-d3/latest/demo/interactive-demo.html?graph=digraph%20%7B%0Arankdir%3DLR%0Aalign%3DDL%0APhase1%20-%3E%20Phase2%0APhase2%20-%3E%20Phase3%0APhase1%20-%3E%20Task1%0ATask1%20-%3E%20Task12%0APhase2%20-%3E%20Task2%0APhase3%20-%3E%20Task3%0A%7D%0A%20%20

You could probably achieve this with rank constraints:

https://github.com/cpettitt/dagre/issues/159

Closing this as a dup of that ticket.

**Comment by xp0522** [comment]
Thanks so much! I will take a look at the rank constraints.
