### ISSUE TITLE
Cluster labels are not visible when cluster has fill color

### ISSUE THREAD

**Issue by dnfeitosa** [cpettitt/dagre-d3#175]
The cluster [demo page](http://cpettitt.github.io/project/dagre-d3/latest/demo/clusters.html) has labels configured for each node group, but it is not visible due the to group fill color:

```
g.setNode('group', {label: 'Group', clusterLabelPos: 'top', style: 'fill: #d3d7e8'});
g.setNode('top_group', {label: 'Top Group', clusterLabelPos: 'bottom', style: 'fill: #ffd47f'});
g.setNode('bottom_group', {label: 'Bottom Group', style: 'fill: #5f9488'});
```
![image](https://cloud.githubusercontent.com/assets/78372/8017380/f6ff857a-0ba8-11e5-87aa-451bc76cea05.png)

It seems the node order is playing some role on how the elements are shown. I was able to get it to be visible by inspecting and manually editing the generated svg and inverting the rect/g.label element positions:
```
<g class="cluster" transform="translate(283.0234375,223)" style="opacity: 1;">
  <rect style="fill: #d3d7e8" width="435.296875" height="273" x="-217.6484375" y="-136.5"></rect>
  <g class="label">
    <g transform="translate(-19.0625,-136.5)"><text><tspan xml:space="preserve" dy="1em" x="1">Group</tspan></text></g>
  </g>
</g>
```
![image](https://cloud.githubusercontent.com/assets/78372/8017414/0afde2dc-0baa-11e5-8849-72df6c8ce0b3.png)

**Comment by cpettitt** [comment]
This was fixed by salerth in https://github.com/cpettitt/dagre-d3/pull/180. It will show up in v0.4.9. Thanks @salerth!
