### ISSUE TITLE
Weird layout

### ISSUE THREAD

**Issue by bsideup** [cpettitt/dagre-d3#201]
Hi!

I'm using LR direction, and seems like algorithm is not optimal for it:
![Demo](https://i.gyazo.com/f9ef1482f71dbb6193611aa942fe0615.png)

Is it possible to make it more..... linear? Something like:
```
[] ----- [] ----- [] ----- []
   \---- [] \---- [] \---- [] 
```

**Comment by bsideup** [comment]
http://bl.ocks.org/jebeck/89fd1b6083a19d7f644a

another example. Why it's going up?

**Comment by cpettitt** [comment]
It is trying to balance nodes. You can force an alignment with the "align" property (valid values: "UL", "UR", "DL", DR").

<img width="622" alt="screen shot 2015-11-24 at 4 48 11 am" src="https://cloud.githubusercontent.com/assets/11766/11367139/9eacd414-9266-11e5-9fdc-98411b53e52e.png">

```
digraph {
rankdir=LR
align=UL

Build -> DeployCI -> DeployQA -> DeployProd -> TestProd
Build -> Sonar
DeployCI -> TestCI
DeployQA -> TestQA
}
```

[Interactive Example](http://cpettitt.github.io/project/dagre-d3/latest/demo/interactive-demo.html?graph=digraph%20%7B%0Arankdir%3DLR%0Aalign%3DUL%0A%0ABuild%20-%3E%20DeployCI%20-%3E%20DeployQA%20-%3E%20DeployProd%20-%3E%20TestProd%0ABuild%20-%3E%20Sonar%0ADeployCI%20-%3E%20TestCI%0ADeployQA%20-%3E%20TestQA%0A%7D%0A%20%20)

**Comment by bsideup** [comment]
@cpettitt oh, this is so great, thanks!

**Comment by bsideup** [comment]
@cpettitt BTW is it documented? Can't find in wiki :(

**Comment by cpettitt** [comment]
I don't think so. It was originally added for debugging, but has turned out to be useful for some real world situations. It would be great to get it on the wiki.

**Comment by bsideup** [comment]
@cpettitt done: https://github.com/cpettitt/dagre/wiki/Home/_compare/795548219eb9a60682234487358fb70c13461064...c1892b0b72b081284ab4318cb3971b62c5b5b080

BTW by default wiki is open for everyone for editing, not sure if it's good :)

**Comment by cpettitt** [comment]
Looks great. Thanks!

**Comment by bsideup** [comment]
Hi @devheroo,

Yes, the screenshot is from my React-based fork of https://github.com/Diabol/delivery-pipeline-plugin

**Comment by devheroo** [comment]
Thanks @bsideup , I appreciate it :)
