### ISSUE TITLE
Chrome 48 removes  SVGGraphicsElement.getTransformToElement()

### ISSUE THREAD

**Issue by rbojha** [cpettitt/dagre-d3#202]
Unfortunately the most recent beta version of chrome (48.0.2564.23) removes `SVGElement.prototype.getTransformToElement` which is [used when creating edges](https://github.com/cpettitt/dagre-d3/blob/40198f90601e2631245f5279a1e0bc63ef079145/lib/create-edge-paths.js#L92). 

The motivation behind removing this feature can be found [here](https://lists.w3.org/Archives/Public/www-svg/2015Aug/att-0009/SVGWG-F2F-minutes-20150824.html#item02) with the actual Google Chrome issue tracking this [here](https://www.chromestatus.com/feature/5736166087196672)

Therefore using `dagre-d3` in this latest beta version of Chrome throws errors like:

>```
TypeError: elem.getTransformToElement is not a function(…)
```

As [suggested by the JointJS team](http://jointjs.com/blog/get-transform-to-element-polyfill.html) this function can be poly-filled where it is required. We are working around this locally with a polyfil for now, but it clearly would be better for `dagre-d3` to centralise a fix (polyfil or otherwise) so that everyone using Chrome 48 can benefit. 

Any thoughts on how best to fix this in `dagre-d3`?

**Comment by myitcv** [comment]
As an example of the impact of this, here is a screenshot of the sentence tokenisation demo in Version 48.0.2564.23 beta (64-bit):

![screen shot 2015-12-09 at 11 25 22](https://cloud.githubusercontent.com/assets/3374574/11684182/a6cb27ce-9e67-11e5-8204-e402bb38070b.png)

**Comment by robhobbes** [comment]
@rbojha, can you post the polyfill you are using? Are you using the same polyfill that JointJS posted?

**Comment by rbojha** [comment]
yes @robhobbes, we are using the same polyfill as JointJs Team posted..

```
SVGElement.prototype.getTransformToElement = SVGElement.prototype.getTransformToElement || function(elem) {
	return elem.getScreenCTM().inverse().multiply(this.getScreenCTM());
};

```

**Comment by cpettitt** [comment]
This should be fixed in 0.4.13 (verified on Chrome 48). If you see any issues please open a new issue. Thanks.

**Comment by jrgleason** [comment]
Wow so the justification for removing this from Chrome was it is too difficult to fix the issues? That sounds like a crappy reason what am I missing?

**Comment by nanchenchen** [comment]
Some notes for people encountering this issue: I also encountered this issue in v0.4.10, and I tried v0.4.13 and found the dagre-d3/dist/dagre-d3.core.js is missing from that version. It turns out that v0.4.17 works for the current version of Chrome.

**Comment by stephenpascoe** [comment]
After deploying this fix I notice these warnings suggesting tooltips will break shortly:
```
tipsy.js:30 'SVGElement.offsetWidth' is deprecated and will be removed in M50, around April 2016. See https://www.chromestatus.com/features/5724912467574784 for more details.
tipsy.js:31 'SVGElement.offsetHeight' is deprecated and will be removed in M50, around April 2016. See https://www.chromestatus.com/features/5724912467574784 for more details.
```

**Comment by davidgilbertson** [comment]
@jrgleason if you're interested, it's been [removed from the SVG spec](https://www.w3.org/TR/SVG2/changes.html#types), it's not just Chrome removing a feature.
