### ISSUE TITLE
v0.3.x does not work in lastest chrome & arrow not shown

### ISSUE THREAD

**Issue by kdh6429** [cpettitt/dagre-d3#209]
Since no reason to update dagre-3d library, I was using v0.3.3.
Chrome has been updated as v48.0.x and path is not shown, and I updated dagre-d3 version(lastest). Everything works but arrow is not shown. 

This is how I fixed it.

  svgPaths.selectAll("path.path")
    .each(function(e) {
      var edge = g.edge(e);
      edge.arrowheadId = _.uniqueId("arrowhead");

      var domEdge = d3.select(this)
        .attr("marker-end", function() {
            **//return "url(" + location.href + "#" + edge.arrowheadId + ")";** // origin code
            **return "url(#" + edge.arrowheadId + ")";** // changed code
        })
        .style("fill", "none");

      util.applyTransition(domEdge, g)
        .attr("d", function(e) { return calcPoints(g, e); });

      util.applyStyle(domEdge, edge.style);
    });

I don't know since when this library starts using location.href in arrow and It's ok with changing code like this, but changing the code looks working well as expect.

**Comment by kdh6429** [comment]
I'm using dagre-d3 chart in single page application with angluar. I might be worng since i'm pretty noob with this area.

**Comment by cpettitt** [comment]
I just recently (2 days ago) took a PR that switched to using location.href: https://github.com/cpettitt/dagre-d3/commit/3e3b057517f70ab0f777542290263821b511219b. In the console can you look at location.href? Does it look right to you? I suspect it may be getting changed by the angular router.

**Comment by kdh6429** [comment]
location.href seems set right in angluar page but arrow is not shown. I have no idea how to check arrow is created correctly or not. I just tried to change url() with suspicion. Any idea to check whether arrow is created or not?

**Comment by mlturbon** [comment]
I think the arrow does not display when the location.href already has a # .

**Comment by pragyesh15** [comment]
I am also facing the same issue.
When I removed the location.href, I am getting arrow like below -
![arrowhead](https://cloud.githubusercontent.com/assets/15924833/12745987/58687588-c9c2-11e5-9fe0-d5ec3837f265.png)

**Comment by pragyesh15** [comment]
I am getting one more issue of edges alignment like below.
![arrowhead](https://cloud.githubusercontent.com/assets/15924833/12750744/1cef72f0-c9df-11e5-801e-5e56a2a950b9.png)

**Comment by cpettitt** [comment]
@mlturbon: Good call. I'm able to repro the issue as you described. I'll take a pass at stripping the fragment portion of the URL and release a new build.

**Comment by cpettitt** [comment]
Release a new build (v0.4.17) that fixes the problem described by @mlturbon. @kdh6429 could you please give it a try and let me know if it resolves your original problem?

**Comment by ianmacartney** [comment]
The missing arrow issue was resolved for me (going from v0.4.14 -> v0.4.17)

**Comment by cpettitt** [comment]
Thanks @ianmacartney!

**Comment by michaelkariv** [comment]
Introducing location + fragment instead of just fragment might solve the original issue but creates a new one for me. I want to 1) export SVG to a file and 2) draw SVG into a Canvas to create PNG out of it. In both cases ther marker-end has the original page URL, and the arrowhead does not show.

**Comment by michaelkariv** [comment]
Should I open a new issue, as this one is closed? Sorry for a noob question

**Comment by kdh6429** [comment]
@michaelkariv better to open new issue and describe more about your problem :)
