### ISSUE TITLE
Need to add xmlns="http://www.w3.org/1999/xhtml" to html labels

### ISSUE THREAD

**Issue by jrgleason** [cpettitt/dagre-d3#216]
Otherwise when I try to output the SVG the FO are note shown

**Comment by jrgleason** [comment]
https://github.com/exupero/saveSvgAsPng/issues/70

**Comment by cpettitt** [comment]
I checked this locally and I see the `http://www.w3.org/1999/xhtml` set as the `namespaceURI` for the div immediately under the foreignObject. Are you seeing something different? If so, can you give me steps to repro?

**Comment by cpettitt** [comment]
Ahh, I see your patch where you're attaching this as an attribute. I'll pull that shortly.

**Comment by jrgleason** [comment]
Was it merged can we close?

**Comment by cpettitt** [comment]
Yep, merged. Thanks!
