### ISSUE TITLE
pathSegList deprecated in Chrome 48

### ISSUE THREAD

**Issue by rmatejka** [cpettitt/dagre-d3#218]
pathSegList has been removed from Chrome 48. It's used in exit:

 var points = _.range(this.pathSegList.length).map(function() { return source; });

Need to be:

          var points = _.range(this.getTotalLength()).map(function () { return source; });

**Comment by cpettitt** [comment]
I'm running Chrome 48.0.2564.97 and not able to repro. Is this removed on a canary?

In any case, I saw something about this on the Chrome side and your proposed change works, so I'm inclined to change this.

Thanks for the heads up.

**Comment by rmatejka** [comment]
I'm running on the same build -  48.0.2564.97 m (64-bit) - but fails:

swRoutegraph.draw TypeError: Cannot read property 'length' of undefined
    at SVGPathElement.<anonymous> (http://rmatejka3-dt.swdev.local/ui/modules/netpath/js/vendor.js:57430:46)
  
which is 
        var points = _.range(this.pathSegList.length).map(function() { return source; });

Thanks for approving the change - we just were about to release our beta when things went south in chrome.
