### ISSUE TITLE
center and zoom fit a large width svg

### ISSUE THREAD

**Issue by djangosdk** [cpettitt/dagre-d3#245]
JSFIDDLE:https://jsfiddle.net/bababalcksheep/xa9rofm5/13/
I am having trouble centering and zoom fitting all contents once dagre is finished.

**Comment by git-ashish** [comment]
This is not really a dagre question, you should try avoiding creating issues for these kind of problems.

Anyway, you can do it like this - 

Updated Fiddle - https://jsfiddle.net/xa9rofm5/14/

// Center the dag
var zoomScale = 1;
// Get Dagre Graph dimensions
var graphWidth = g.graph().width + 80;
var graphHeight = g.graph().height + 0;
// Get SVG dimensions
var width = parseInt(svg.style("width").replace(/px/, ""));
var height = parseInt(svg.style("height").replace(/px/, ""));

// Calculate applicable scale for zoom
zoomScale = Math.max( Math.min(width / graphWidth, height / graphHeight));

var translate = [(width/2) - ((graphWidth*zoomScale)/2), 0];
zoom.translate(translate);
zoom.scale(zoomScale);
zoom.event( inner );

**Comment by djangosdk** [comment]
works.

**Comment by djangosdk** [comment]
This should be provided in examples.

**Comment by git-ashish** [comment]
Although documentation can be improved, demos do have the information which can be used for custom requirements. For e.g. check this out https://github.com/cpettitt/dagre-d3/blob/master/demo/clusters.html#L96
