### ISSUE TITLE
Event on clicking edge labels

### ISSUE THREAD

**Issue by lynerjy** [cpettitt/dagre-d3#254]
Hi, I'm trying to have two labels attached to each edge.. one "+" and one "-", where if the "+" is clicked, the edge increases thickness, and if the "-", then it decreases. 

How do I drive events from the edge labels being clicked..?

**Comment by git-ashish** [comment]
After the rendering, you can use d3 to select those elements and bind events.

**Comment by lynerjy** [comment]
Got it! Thanks!
