### ISSUE TITLE
Edge id on click?

### ISSUE THREAD

**Issue by lynerjy** [cpettitt/dagre-d3#255]
I'm trying to change an edge colour when that edge is clicked. I get that I can use this to detect the click on the edge:

`svg.selectAll("g.edgePath").on("click", function(id) { });`

But how do i return the id of that particular edge so that I might manipulate its attributes..?

**Comment by git-ashish** [comment]
svg.selectAll("g.edgePath").on("click", function(id) { 

// You can access the dom element like this
var domElement = this;

});

**Comment by lynerjy** [comment]
Awesome thank you!
