### ISSUE TITLE
How do I increase distance between nodes? 

### ISSUE THREAD

**Issue by minecraft2048** [cpettitt/dagre-d3#256]
Let say I follow the TCP state diagram demo: http://cpettitt.github.io/project/dagre-d3/latest/demo/tcp-state-diagram.html

I want to tweak it so that the vertical distance between let say, CLOSED and LISTEN is x unit. What parameters can I tweak in dagre-d3 so I can increase the rank node separation, like Graphviz `ranksep` parameter or vis.js `levelSeparation` ?

Also, it is possible to set the rank separation between only 2 layer, let say i want to increase the vertical distance between LISTEN and SYN_RCVD but keep the CLOSED and LISTEN vertical distance constant?

I have read dagre-d3, dagre and graphlib documentation, but I still don't get it

**Comment by minecraft2048** [comment]
More investigation: I found this: https://github.com/paralin/meteor-dagre-d3 which states that 
```
var layout = dagreD3.layout()
                    .nodeSep(20)
                    .rankDir("LR");
renderer.layout(layout).run(g, d3.select("svg g"));
```
can be used to customize the layout, and `.nodeSep` is the way to customize node distance, as with `ranksep` in https://github.com/cpettitt/dagre/wiki#using-dagre, but apparently renderer is deprecated and changed with render, as per this commit:
```
commit 09b395f0540e3986d1874eff43c30e6a0d879a57
Author: Chris Pettitt <cpettitt@gmail.com>
Date:   Sun Oct 12 21:04:31 2014 -0700

    Remove old renderer

 delete mode 100644 lib/Renderer.js
```
So how do I use `render` instead of `renderer` to change the layout then?

**Comment by minecraft2048** [comment]
bump

**Comment by aamory** [comment]
This may not give you everything you need, but have you tried using the parameters in .setGraph()? 
```javascript
var g = new dagreD3.graphlib.Graph()
  .setGraph({rankdir: 'LR', edgesep: 10, ranksep: 60, nodesep: 10})
  .setDefaultEdgeLabel(function() { return {}; });

g.setNode("A",  { label: "A"});
g.setNode("B",  { label: "B"});
g.setNode("C",  { label: "C"});

g.setEdge("A", "C");
g.setEdge("B", "C");

var render = new dagreD3.render();

var svg = d3.select("svg"),
    svgGroup = svg.append("g");

render(d3.select("svg g"), g);
```

**Comment by minecraft2048** [comment]
It works! thank you
