### ISSUE TITLE
How do I change edge color that is connected to a node?

### ISSUE THREAD

**Issue by minecraft2048** [cpettitt/dagre-d3#259]
Lets use the TCP state diagram again: http://cpettitt.github.io/project/dagre-d3/latest/demo/tcp-state-diagram.html

How do I modify it so when I click on SYN SENT, the surrounding edges, which are send, close, rcv SYN and rcv SYN,ACK turns red from black?

Currently I can get the node SVG class from https://github.com/cpettitt/dagre-d3/issues/255, by using 
```
svg.selectAll("g.nodePath").on("click", function(id) {

// You can access the dom element like this
var domElement = this;

});
``` 
instead of 
```
svg.selectAll("g.edgePath").on("click", function(id) {

// You can access the dom element like this
var domElement = this;

});
```
, and according to https://github.com/cpettitt/dagre-d3/issues/114, there is an API that returns the child, but as we all know that this project barely have documentation, https://github.com/cpettitt/dagre-d3/issues/242 , so how do I do this?

**Comment by git-ashish** [comment]
You can get node edges via - 

1. Get all node edges ( Both Incoming and Outgoing) - graph.nodeEdges("SYN SENT")

2. Get all Incoming edges - graph.inEdges("SYN SENT")

3. Get all Outgoing edges - graph.outEdges("SYN SENT")

Pseudo algo - 

Things to do before rendering - 

1. Assign unique id to every node.
2. When setting an edge, use the node id for the node it connects and add it in the classname like this - 
g.setEdge("SYN RCVD", "CLOSE WAIT", {class:"in-node_1 out-node_2", label: "CHECK-IT-OUT"});

Event binding - 

svg.selectAll("g.nodePath").on("click", function(d,i) {

// You can access the dom element like this
var domElement = this;

// get bound node data - 
var data = d;

// get the id of the node ( if stored earlier in the node data; via usual data assignment; lets call it cid )

// select all incoming / outgoing edges
d3.selectAll("g.edgePath.in-"+data.cid)
.style("stroke", "red"); // or use classnames with predefined properties.

});

});

**Comment by minecraft2048** [comment]
How do I get the id of the node?
`// get the id of the node ( if stored earlier in the node data; via usual data assignment; lets call it cid )`
I think you missed a code there

**Comment by git-ashish** [comment]
You can preprocess your dataset and assign each node a unique id. Let's assume your node dataset is an array of object which looks like this  

`{id:'node-1', label: 'Go Red', properties: { a: 1, b: 'hello'} }`

After the dataset processing, you have an id attribute which uniquely identifies a node.

When adding nodes to the graph, you can use - 


```
// Add node to graph
g.setNode( nodeObj.id, { 
    label: nodeObj.label,
    //labelType: "html",
    //label: html, // your html code here
    // class: className, // any desired custom class names
    shape: "rect",
    paddingLeft: 0,
    paddingRight: 0,
    paddingTop: 0,
    paddingBottom: 0,
    data: nodeObj, // You can save your node data object here for later use during events
    width: 100,
    height: 60
});
```

Now, when click event on a node gets triggered - 


```
svg.selectAll("g.nodes").on("click", function(d,i) {

// You can access the dom element like this
var domElement = this;

// get bound node data - 
var data = d; // this object would have a 'data' property which we previously assigned during node setting

// get the id of the node ( if stored earlier in the node data; via usual data assignment; lets call it id )
// data.id should work and give you the pre-assigned node id ( do not use a numeric id; use a mix with char and numeric like node-1; )

});
```

**Comment by minecraft2048** [comment]
It works again! thank you

**Comment by lynerjy** [comment]
Very helpful, thanks! I'm trying to do something very similar, but I want to change the colour of the edge label instead. How do I refer to the edge label if I know the edge id? 

I have given all my edges the class "e-1", "e-2", etc. but can't seem to point to an edge. I.e. the following doesn't work: d3.selectAll("g.edgeLabel.e-1")
